version: '2.4'
services: 
    revokechain-api:
        depends_on: 
            - api-gateway
        build: 
            context: ./rc-app/node/revokechain-api
            dockerfile: Dockerfile
        volumes: 
            - ./rc-app/node/revokechain-api:/app
        ports:
            - 3000:3000
        environment: 
            - NODE_ENV=${NODE_ENV}
            - NODE_PORT=${NODE_PORT}
            - URL_GATEWAY=${URL_GATEWAY}
            - CHANNEL_NAME=${CHANNEL_NAME}
            - CHAINCODE_NAME=${CHAINCODE_NAME}
            - MSP_NAME=${MSP_NAME}
            - USER_ID=${USER_ID}
            - WALLET_PATH=${WALLET_PATH}
            - CONNECTION_PATH=${CONNECTION_PATH}

    api-gateway:
        build: 
            context: ./krakend-gateway
            dockerfile: Dockerfile
        volumes: 
            - ./krakend-gateway/config:/opt/config
        ports:
            - 80:8080